### ISSUE TITLE
How to invoke python interpreter from C++

### ISSUE THREAD

**Issue by TheButlah** [pybind/pybind11_bazel#14]
Could you provide a rule or example of how to invoke the python interpreter from C++? in the CMake version of pybind, you add `pybind11::embed` as a dependency to your build target. How do we do this in bazel?

**Comment by M-Kerr** [comment]
I’ll post a guide tomorrow.

**Comment by M-Kerr** [comment]
1. In order to embed the python interpreter, we need to find the necessary compiler and linker
    flags for the specific python build intended to be embedded.

    1a.) Find the `python<version>-config` file located in the root python installation's bin directory (virtual envs don't symlink this file). python-config is a script that outputs the compiler and linker flags/options required to embed the python build in native code.

    1b.) For the compiler flags, in the shell cd to the bin directory and run:
            `python<version>-config --cflags`

    - note: ignore the `-I` flag output, this is handled by pybind11 and will make Bazel complain.

    1c.) For the linker flags, if Python version >=3.8 run in the shell:
            `python<version>-config --ldflags --embed`

    - note: --embed is new to Python 3.8 and is not yet in the Python documentation

        Else if Python version <3.8 run in the shell:
            `python<version>-config --ldflags`

2. Add the compiler and linker flags to the `copts` and `linkopts` of the target that includes
    `"pybind11/embed.h"` (usually your application's main cc_binary). Don't include the 
    `-I` compiler flag that was output.

3. Add "@pybind11" to the deps of the target in step 2.

4. `bazel build //...`

**Comment by M-Kerr** [comment]
I'll submit a PR tomorrow or early next week attempting to automatically apply the above logic. It may warrant discussion because Bazel is strict with its hermeticism and determinism requirements.
