### ISSUE TITLE
http-archive

### ISSUE THREAD

**Issue by amatii** [pybind/pybind11_bazel#24]
I am a newbie in bazel.
I have this in my WORKSPACE:

`http_archive(
  name = "pybind11_bazel",
  strip_prefix = "pybind11-2.5.0",
  urls = ["https://github.com/pybind/pybind11/archive/v2.5.0.tar.gz"],
)

http_archive(
  name = "pybind11",
  build_file = "@pybind11_bazel//:pybind11.BUILD",
  strip_prefix = "pybind11-2.5.0",
  urls = ["https://github.com/pybind/pybind11/archive/v2.5.0.zip"],
)
load("@pybind11_bazel//:python_configure.bzl", "python_configure")
python_configure(name = "local_config_python")`

but I get this error:

`ERROR: Every .bzl file must have a corresponding package, but '@pybind11_bazel//:python_configure.bzl' does not have one. Please create a BUILD file in the same or any parent directory. Note that this BUILD file does not need to do anything except exist.`

Do you have any idea how to fix it?

**Comment by codefables** [comment]
Hi amatii. It seems like you're using the same URL for both pybind11 and pybind11_bazel. At the moment pybind11_bazel doesn't seem to provide a stable version, so replacing
```
http_archive(
    name = "pybind11_bazel",
    strip_prefix = "pybind11-2.5.0",
    urls = ["https://github.com/pybind/pybind11/archive/v2.5.0.tar.gz"],
)
```
with
```
git_repository(
    name = "pybind11_bazel",
    branch = "master",
    remote = "https://github.com/pybind/pybind11_bazel.git",
)
```

might help

**Comment by chuckx** [comment]
As @codefables mentioned, **you're not providing a URL for this repository in your pybind11_bazel `http_archive` rule**.

While using a `git_repository` rule will work, it's worth noting that [using the `git_repository` rule is advised against in the Bazel documentation](https://docs.bazel.build/versions/master/external.html#repository-rules).

GitHub allows you to specify either a release tag or a commit hash in repository archive URLs. This repository has no tagged releases as of yet, so you can must use the latter.

You can find the most recent commit by referencing the latest entry in [the commit log](https://github.com/pybind/pybind11_bazel/commits/master).

Given [the current latest commit](https://github.com/pybind/pybind11_bazel/commit/203508e14aab7309892a1c5f7dd05debda22d9a5), here's an example of a valid `http_archive` rule:

```
http_archive(
    name = "pybind11_bazel",
    strip-prefix = "pybind11-203508e14aab7309892a1c5f7dd05debda22d9a5",
    urls = ["https://github.com/pybind/pybind11_bazel/archive/203508e14aab7309892a1c5f7dd05debda22d9a5.zip"]
)
```
