### ISSUE TITLE
undefined symbol: PyThread_tss_alloc

### ISSUE THREAD

**Issue by TheButlah** [pybind/pybind11_bazel#25]
After updating my dependency on pybind11_bazel to the latest commit (https://github.com/pybind/pybind11_bazel/commit/26973c0ff320cb4b39e45bc3e4297b82bc3a6c09) from the previous commit I was using (https://github.com/pybind/pybind11_bazel/commit/ff4dc13aef9dd87dccbc844f12b8af59d023148c), I now get the following error when attempting to import a .so file produced by `bazel build //:whatever`:

```python
import whatever.so
ImportError: /home/ryan/Programming/robotics/bazel-bin/whatever.so: undefined symbol: PyThread_tss_alloc
```
Any ideas? I'm running Python 3.6, and I see that tss_alloc is a python 3.7 feature

**Comment by TheButlah** [comment]
I actually this is due to #26 - python_embed is using the 3.8 version of python, while the actual python interpreter is 3.6.

**Comment by yutongs-dmai** [comment]
> I actually think this is due to #26 - python_embed is using the 3.8 version of python, while the actual python interpreter is 3.6.

Did you solve it by resetting the env?

**Comment by TheButlah** [comment]
I believe so
