### ISSUE TITLE
Any way for python_configure() to use the python toolchain?

### ISSUE THREAD

**Issue by TheButlah** [pybind/pybind11_bazel#26]
Toolchains are the "official" way to specify the version of python to use. I recently transitioned to using a toolchain to inform bazel of my python version, rather than relying on the autodetected version via the PATH variable/an activated venv.

Looking at the code in `python_configure.bzl`, it looks like `python_configure()` bypasses the toolchain completely in favor of invoking the version of python accessible in the system PATH. This gives unintended behavior - in my case, its using the system installed python instead of the version of python I specified in the toolchain.

Is there anyone out there knowledgeable in the ways of bazel that can get the repo rule to use the python toolchain instead?

Pinging @M-Kerr as the original author of python_configure.bzl in case he has any ideas

**Comment by M-Kerr** [comment]
Hmm, I didn’t author the config file but I did add embedding support off the existing functionality. I believe python_configure.bzl is an excerpt from the [tensorflow repository.](https://github.com/tensorflow/tensorflow/blob/master/third_party/py/python_configure.bzl
)
Quickly looking, it seems to get python from an environment variable PYTHON_BIN_PATH, which in tensorflow is set in the  
[//configure script.](https://github.com/tensorflow/tensorflow/blob/master/configure
)
i’m not sure how the variable is set in pybind11_bazel.

Sorry I don’t have more I can look deeper in a few days.

**Comment by newkozlukov** [comment]
Solving this issue should allow fully-reproducible builds with https://github.com/tweag/rules_nixpkgs

I'm not taking a shot at this _right now_, as my familiarity with bazel is, so far, limited to a single failed build attempt

**Comment by bcebere** [comment]
Hello.

I have the same issue. 

Is there a way to use the interpreter set from `register_toolchains` instead of the system one?

I am trying to follow this tutorial https://thethoughtfulkoala.com/posts/2020/05/16/bazel-hermetic-python.html
But I get an error from the pybind11 extension `Python version mismatch`.

**Comment by newkozlukov** [comment]
@bcebere I couldn't figure out how to bridge pybind11_bazel with toolchains in meaningful time, but as a temporary hack - I ended up just running bazel inside Nix shell (effectively enforcing that the detected "global" python is pinned and reproducible)... if that'd be of any help

**Comment by quval** [comment]
We added a patch for this:

```
--- a/python_configure.bzl
+++ b/python_configure.bzl
@@ -154,6 +154,9 @@

 def _get_python_bin(repository_ctx):
     """Gets the python bin path."""
+    if repository_ctx.attr.python_interpreter_target != None:
+        return str(repository_ctx.path(repository_ctx.attr.python_interpreter_target))
+
     python_bin = repository_ctx.os.environ.get(_PYTHON_BIN_PATH)
     if python_bin != None:
         return python_bin
@@ -391,6 +394,7 @@
     ],
     attrs = {
         "python_version": attr.string(default=""),
+        "python_interpreter_target": attr.label(),
     },
 )
 """Detects and configures the local Python.
```

This works well with our hermetic Python setup.

**Comment by TheButlah** [comment]
@quval Could you submit this as a PR to this repo?

**Comment by quval** [comment]
Sure, will do soon. (And actually, the patch was partial; the genrule needs to be local as well. Editing above.)

**Comment by jiawen** [comment]
Any motion on this issue? I'm happy to contribute a PR.

**Comment by bbstilson** [comment]
Bumping

**Comment by junyer** [comment]
As of the [v2.11.1.bzl.2](https://github.com/pybind/pybind11_bazel/releases/tag/v2.11.1.bzl.2) release, pybind11_bazel uses rules_python and no longer involves itself in toolchain shenanigans **_at all_**.
