### ISSUE TITLE
Linker errors with pybind11_embed and static libpython36.a

### ISSUE THREAD

**Issue by TheButlah** [pybind/pybind11_bazel#28]
I get the following error when building a cc_library that has `@pybind11//:pybind11_embed` in `deps`:
```bash
/usr/bin/ld.gold: error: /home/ryan/.pyenv/versions/3.6.9/lib/python3.6/config-3.6m-x86_64-linux-gnu/libpython3.6m.a(object.o): requires dynamic R_X86_64_PC32 reloc against 'stderr' which may overflow at runtime; recompile with -fPIC
/usr/bin/ld.gold: error: /home/ryan/.pyenv/versions/3.6.9/lib/python3.6/config-3.6m-x86_64-linux-gnu/libpython3.6m.a(obmalloc.o): requires dynamic R_X86_64_PC32 reloc against 'stderr' which may overflow at runtime; recompile with -fPIC
/usr/bin/ld.gold: error: /home/ryan/.pyenv/versions/3.6.9/lib/python3.6/config-3.6m-x86_64-linux-gnu/libpython3.6m.a(unicodeobject.o): requires dynamic R_X86_64_PC32 reloc against 'stderr' which may overflow at runtime; recompile with -fPIC
/usr/bin/ld.gold: error: /home/ryan/.pyenv/versions/3.6.9/lib/python3.6/config-3.6m-x86_64-linux-gnu/libpython3.6m.a(_warnings.o): requires dynamic R_X86_64_PC32 reloc against 'stderr' which may overflow at runtime; recompile with -fPIC
```
etc...

I'm assuming that this is because I'm linking a `.a` file (`pyenv` only uses .a files instead of .so) into a `.so` file. What is the right way to fix this?

**Comment by junyer** [comment]
As of the [v2.11.1.bzl.2](https://github.com/pybind/pybind11_bazel/releases/tag/v2.11.1.bzl.2) release, pybind11_bazel uses rules_python and the `pybind11_embed` target no longer exists. Please try using `@rules_python//python/cc:current_py_cc_libs` instead; if that has any problems, please file a new issue (feel free to loop me in!) with the https://github.com/bazelbuild/rules_python project.
