### ISSUE TITLE
No Archives. No longer working?

### ISSUE THREAD

**Issue by yaadhavraajagility** [pybind/pybind11_bazel#31]
In
```
http_archive(
  name = "pybind11_bazel",
  strip_prefix = "pybind11_bazel-<stable-commit>",
  urls = ["https://github.com/pybind/pybind11_bazel/archive/<stable-commit>.zip"],
)
```
The URL `https://github.com/pybind/pybind11_bazel/archive/` doesnt exist

**Comment by chuckx** [comment]
You have to construct a URL using the format specified.

For example, here's the URL which points to the current latest commit (992381ced716ae12122360b0fbadbc3dda436dbf):

https://github.com/pybind/pybind11_bazel/archive/992381ced716ae12122360b0fbadbc3dda436dbf.zip
