### ISSUE TITLE
How do I set a different Python Binary / Lib?

### ISSUE THREAD

**Issue by yaadhavraajagility** [pybind/pybind11_bazel#33]
It says:
```
"""Repository rule for Python autoconfiguration.
`python_configure` depends on the following environment variables:
  * `PYTHON_BIN_PATH`: location of python binary.
  * `PYTHON_LIB_PATH`: Location of python libraries.
"""
```
But I did set those variables but bazel doesnt seem to receive/respect them?

**Comment by yaadhavraajagility** [comment]
@M-Kerr @TheButlah Anyone knows how?

**Comment by Mizux** [comment]
@yaadhavraajagility which OS did you use ?

**Comment by junyer** [comment]
As of the [v2.11.1.bzl.2](https://github.com/pybind/pybind11_bazel/releases/tag/v2.11.1.bzl.2) release, pybind11_bazel uses rules_python. Please refer to the latter's [documentation](https://rules-python.readthedocs.io/en/latest/getting-started.html) for details about registering toolchains.
