### ISSUE TITLE
pybind_extension without 'local' tag

### ISSUE THREAD

**Issue by virgile-hogman** [pybind/pybind11_bazel#34]
hi,
why does the `pybind_extension` rule enforce the `local` tag? This prevents the remote caching of the binary module.

We generate several python modules in CI, some are very expensive to build. I think we would benefit from caching it.

Description of `local` from [tags](https://docs.bazel.build/versions/main/be/common-definitions.html#common-attributes):
> local keyword precludes the action or test from being remotely cached, remotely executed, or run inside the sandbox. For genrules and tests, marking the rule with the local = True attribute has the same effect.

If we want to keep "no remote execution" or "no sandbox" it should not be a problem, though I'd rather leave these options open unless there's a good counter argument. What is the reason for disabling them?

Initially there was even a `manual` tag  that has been removed in #13. Can't we do the same here?

**Comment by virgile-hogman** [comment]
I can understand there might be some concerns about the size of the binary module which tend to be pretty huge... But that decision should rather be in the hands of the users.

In fact more than the binary module it's the `obj` files produced by sources defined in `pybind_extension` that we want to cache. It's the compilation task that is massive, the linker is peanuts in comparison. We could have a workaround with an intermediate `pybind_library` that allows remote caching but that feels quite twisted. What makes the `pybind_extension` different from a regular `cc_binary` target?

**Comment by virgile-hogman** [comment]
@chuckx sorry if I bother you, but since you answered #13 you may have some insights here.
Could it just be the case that the `local` tag was put in combination with `manual`? But now since `manual` is gone `local` is not needed anymore? 
We are testing this in CI without `local` with a custom patch. I don't see any reason why it wouldn't work, but I'll let you know.

**Comment by chuckx** [comment]
>... But that decision should rather be in the hands of the users.

That seems totally reasonable to me. Will merge the PR.

FYI, portions of the current implementation are artifacts from the initial export that should be reconsidered and potentially changed.
