### ISSUE TITLE
textual_hdrs

### ISSUE THREAD

**Issue by lkjell** [pybind/pybind11_bazel#4]
Since pybind11 is header only library shouldn't the header files be defined under `textual_hdrs` instead of `hdrs`?

https://docs.bazel.build/versions/master/be/c-cpp.html#cc_library.textual_hdrs

**Comment by jsharpe** [comment]
No, `textual_hdrs` is for files that are transitively included by other headers but can't be compiled on their own. `hdrs` is the correct attribute to be used for the targets.

**Comment by jblespiau** [comment]
Closing, as it's very old, we can consider it's obsolete. Feel free to open a new bug if still topical.
