### ISSUE TITLE
Relative path used for _get_python_include, when using python_interpreter_target

### ISSUE THREAD

**Issue by andersdyhrnorlov** [pybind/pybind11_bazel#45]
I had an issue where I would get /install/include/python3.10 from _get_python_include when using python_interpreter_target in python_configure. When I use the local python version everything seems to work as expected. Since I only got the relative path the build would fail, as it could not find the include directory. 

Creating a local version of python_configure.bzl I found that the following code:

```
def _get_python_include(repository_ctx, python_bin):
    """Gets the python include path."""
    result = _execute(
        repository_ctx,
        [
            python_bin,
            "-c",
            "from __future__ import print_function;" +
            "from sysconfig import get_paths;" +
            "print(get_paths()['include']);",
        ],
        error_msg = "Problem getting python include path.",
        error_details = ("Is the Python binary path set up right? " +
                         "(See ./configure or " + _PYTHON_BIN_PATH + ".) " +
                         "Is distutils installed?"),
    )

    return result.stdout.splitlines()[0]
```

would create the full path to the include folder both with local and python_interpreter_target. I'm pretty new to bazel so maybe I'm doing something wrong, that causes it to return a relative path. But maybe this change could be useful?

**Comment by rwgk** [comment]
Hm, interesting.

So the diff is essentially (made up):

```diff
-get_path('include')
+get_paths()['include']
```

I looked at the sysconfig.py code in Python 3.10, copying here for easy reference:

```
def get_paths(scheme=get_default_scheme(), vars=None, expand=True):
    """Return a mapping containing an install scheme.

    ``scheme`` is the install scheme name. If not provided, it will
    return the default scheme for the current platform.
    """
    if expand:
        return _expand_vars(scheme, vars)
    else:
        return _INSTALL_SCHEMES[scheme]


def get_path(name, scheme=get_default_scheme(), vars=None, expand=True):
    """Return a path corresponding to the scheme.

    ``scheme`` is the install scheme name.
    """
    return get_paths(scheme, vars, expand)[name]
```

That looks like your modification should give exactly the same result as what's currently in this repo. Could you please double-check? Maybe some other change in your environment fixed your issue?

**Comment by andersdyhrnorlov** [comment]
Interesting seems like you are correct using `get_path('include')` works just as well. However, when I load python_configure with: `load("@pybind11_bazel//:python_configure.bzl", "python_configure")` I only get the relative path and get the error: 
```
Error in fail: Python Configuration Error: Repository command failed
find: /install/include/python3.10: No such file or directory
```

But when using a local version of your python configure `load("//_build_rules/python/pybind11:python_configure.bzl", "python_configure")` everything seems to work.

**Comment by rwgk** [comment]
@rickeylev Do you happen to know how

```diff
-load("@pybind11_bazel//:python_configure.bzl", "python_configure")
+load("//_build_rules/python/pybind11:python_configure.bzl", "python_configure")
```

leads to different behavior? See [previous comment](https://github.com/pybind/pybind11_bazel/issues/45#issuecomment-1303042677) here for the full description of the problem.

**Comment by rickeylev** [comment]
Is there a diff you can show me for more context? I don't know what file/code that diff is being applied to.

In general, though, the difference is "load(@pybind11_bazel//:bar.bzl)" means to load the version of the code the repository "foo" (as configured in WORKSPACE) points to. In comparison, "load(//:bar.bzl)" means to load the code within the repository the load is occurring in.

It's probably possible to craft a WORKSPACE such that you up in a situation where "pybind11_bazel" points to one snapshot of code (e.g. a tar.gz download from github), while "current repository" points to another (e.g. the local disk). Within the pybind11_bazel codebase, I would recommend always omitting the expected self-name when loading its own code.

I don't know why this would manifest as a local vs relative path being returned. I'm not too familiar with repository rules.

**Comment by rwgk** [comment]
> Within the pybind11_bazel codebase, I would recommend always omitting the expected self-name when loading its own code.

I think we do, or to be more precise, the only self-references are in README.md. See below.

@jblespiau Do you happen to know why [this happens](https://github.com/pybind/pybind11_bazel/issues/45#issuecomment-1303042677)?

```
$ grep --exclude-dir .git -r -e '@pybind11_bazel' -e 'load('
py/BUILD.tpl:load("@bazel_tools//tools/python:toolchain.bzl", "py_runtime_pair")
README.md:  build_file = "@pybind11_bazel//:pybind11.BUILD",
README.md:load("@pybind11_bazel//:python_configure.bzl", "python_configure")
README.md:load("@pybind11_bazel//:build_defs.bzl", "pybind_extension")
pybind11.BUILD:load("@rules_cc//cc:defs.bzl", "cc_library")
```

**Comment by jblespiau** [comment]
No, sorry, I don't. For me, `load("@pybind11_bazel//:python_configure.bzl", "python_configure")` is the normal wayto import is, and I have no idea what `load("//_build_rules/python/pybind11:python_configure.bzl", "python_configure")` is (I have no idea what `_build_rules` is).

**Comment by andersdyhrnorlov** [comment]
@rwgk sorry for the late reply. I'm running on macos with arm cpu. I've added our build system example. Line 234 and 235 in the WORKSPACE file is were I load either my downloaded version or your version of python_configure.

If I run bazel test //... it will run fine with my local version, but using yours it will fail with the error described above.

[bazel-build-system-example.zip](https://github.com/pybind/pybind11_bazel/files/10010167/bazel-build-system-example.zip)

**Comment by rwgk** [comment]
Sorry I got to looking at the .zip file only now.

Note that I don't know much about bazel. (My domain is the C++ bindings code.)

I see this:

```
$ ls -1 _build_rules/python/pybind11
BUILD.bazel
BUILD.tpl
python_configure.bzl
```

The only non-whitespace diff for python_configure.bzl is this:
```
 def _tpl(repository_ctx, tpl, substitutions = {}, out = None):
     if not out:
         out = tpl
     repository_ctx.template(
         out,
-        Label("//py:%s.tpl" % tpl),
+        Label("//_build_rules/python/pybind11:%s.tpl" % tpl),
         substitutions,
     )
```

Looking at the top-level of the unpacked zip file:

```
$ ls -1 BUILD*
BUILD.bazel
```

That makes me think it's simply not finding the `BUILD.tpl` file it is looking for.

Do you see a warning or error about the missing BUILD.tpl file when using `load("@pybind11_bazel//:python_configure.bzl", "python_configure") `?

I'm guessing if you move or copy your BUILD.tpl to the top level you don't need to patch python_configure.bzl
Could you please try?

I don't know if this is something we need to fix in pybind11_bazel, or if that's something that needs to be documented.

@rickeylev @jblespiau @chuckx does this ring any bells?  —  Concretely: do users have to provide a `BUILD.tpl` file?

**Comment by andersdyhrnorlov** [comment]
I don't see a missing template error I only get this error:

```
Error in fail: Python Configuration Error: Repository command failed
find: /install/include/python3.10: No such file or directory
```

I tried placing the build template in the root, but that didn't change anything. I'm actually unsure what `//py` is referering to in your code, in that label.

**Comment by rwgk** [comment]
I'm actually unsure what `//py` is referering to in your code, in that label.

Oh ... I guess this you mean this?

> -        Label("//py:%s.tpl" % tpl),

Sorry I overlooked that.

I looked around a bit now, I think it's this:

https://github.com/pybind/pybind11_bazel/tree/master/py

Note the BUILD.tpl file there.

I played around also, using pybind11_abseil as a test bed, changing the WORKSPACE file there like this:

```
local_repository(
    name = "pybind11_bazel",
    path = "/usr/local/google/home/rwgk/forked/pybind11_bazel",
)
```

After I convinced myself that it works with pybind11_bazel as-is, I removed the py/BUILD.tpl file. That leads to an obvious error message, essentially "BUILD.tpl file not found". If you don't see that error, it's definitely finding the file (good).

The next thing I noticed is that we have this in a script under pybind11_abseil, which sets up the environment before calling `bazel test`:

```
export PYTHON_BIN_PATH=`which python3`
export PYTHON_LIB_PATH=`python3 -c "import sysconfig; print(sysconfig.get_path('include'))"`
echo "Using PYTHON_BIN_PATH: $PYTHON_BIN_PATH"
echo "Using PYTHON_LIB_PATH: $PYTHON_LIB_PATH"
```

But the pybind11_abseil tests succeed even with this commented out.

Note that I'm using the system Python (/usr/bin/python3, happens to be 3.10). Apparently the automatic discovery in works for that. But maybe it doesn't work for your environment?

You had:
```
/install/include/python3.10
```

Are you using a non-system Python?

But in any case, could you try to `export` `PYTHON_BIN_PATH` & `PYTHON_LIB_PATH` with the correct paths before running bazel?

If that doesn't help, could you please try to

```
git clone https://github.com/pybind/pybind11_bazel.git
```

apply this patch

```diff
diff --git a/python_configure.bzl b/python_configure.bzl
index 7c8fa59..047d909 100644
--- a/python_configure.bzl
+++ b/python_configure.bzl
@@ -252,6 +252,7 @@ def _check_python_bin(repository_ctx, python_bin):

 def _get_python_version(repository_ctx, python_bin):
     """Returns a tuple (major_version, minor_version)."""
+    print("LOOOK", "_get_python_version", "python_bin", python_bin)
     result = _execute(
         repository_ctx,
         [
@@ -262,6 +263,7 @@ def _get_python_version(repository_ctx, python_bin):
         error_msg = "Problem getting Python version using binary " + python_bin,
         error_details = "",
     )
+    print("LOOOK", "_get_python_version", "result.stdout.splitlines()", result.stdout.splitlines())
     version = result.stdout.splitlines()[0].split(".")
     version = (int(version[0]), int(version[1]))
     return version
@@ -269,6 +271,7 @@ def _get_python_version(repository_ctx, python_bin):
 def _get_python_include(repository_ctx, python_bin):
     """Gets the python include path."""
     version = _get_python_version(repository_ctx, python_bin)
+    print("LOOOK", "_get_python_include", version)
     result = _execute(
         repository_ctx,
         [
@@ -280,6 +283,7 @@ def _get_python_include(repository_ctx, python_bin):
         error_details = ("Is the Python binary path set up right? " +
                          "(See ./configure or " + _PYTHON_BIN_PATH + ".)"),
     )
+    print("LOOOK", "_get_python_include", "result.stdout.splitlines()", result.stdout.splitlines())
     return result.stdout.splitlines()[0]

 def _get_python_import_lib_name(repository_ctx, python_bin):

```

and point `local_repository()` to that local repo like I did (above)?

With that I'm seeing this:

```
DEBUG: /usr/local/google/home/rwgk/.cache/bazel/_bazel_rwgk/b34ed657d207ca0467e56fc9cb2fbaaf/external/pybind11_bazel/python_configure.bzl:255:10: LOOOK _get_python_version python_bin /usr/local/google/home/rwgk/tmp/pybind11_abseil/venv/bin/python
DEBUG: /usr/local/google/home/rwgk/.cache/bazel/_bazel_rwgk/b34ed657d207ca0467e56fc9cb2fbaaf/external/pybind11_bazel/python_configure.bzl:266:10: LOOOK _get_python_version result.stdout.splitlines() ["3.10"]
DEBUG: /usr/local/google/home/rwgk/.cache/bazel/_bazel_rwgk/b34ed657d207ca0467e56fc9cb2fbaaf/external/pybind11_bazel/python_configure.bzl:274:10: LOOOK _get_python_include (3, 10)
DEBUG: /usr/local/google/home/rwgk/.cache/bazel/_bazel_rwgk/b34ed657d207ca0467e56fc9cb2fbaaf/external/pybind11_bazel/python_configure.bzl:286:10: LOOOK _get_python_include result.stdout.splitlines() ["/usr/include/python3.10"]
```

**Comment by junyer** [comment]
As of the [v2.11.1.bzl.2](https://github.com/pybind/pybind11_bazel/releases/tag/v2.11.1.bzl.2) release, pybind11_bazel uses rules_python and `python_configure.bzl` no longer exists.
