### ISSUE TITLE
Incompatible with remote execution

### ISSUE THREAD

**Issue by cameron-martin** [pybind/pybind11_bazel#48]
In python_configure.bzl, [a genrule is created that symlinks the headers from the python installation](https://github.com/pybind/pybind11_bazel/blob/faf56fb3df11287f26dbc66fdedf60a2fc2c6631/python_configure.bzl#L360-L365). This determines the location of these headers during repository rule execution then uses it during execution, assuming that this location still exists. This assumption is not correct when using remote execution and results in the following error:

```
ERROR: /localdata/cameronm/bazel-cache/_bazel_cameronm/4a6a9c9dd102688bd8fbfeb685efb169/external/local_config_python/_python3/BUILD:25:8: Executing genrule @local_config_python//_python3:_python3_include failed: (Exit 34): Invalid action cache entry 1fbde1c0993f3d186ff6ade516bfd2765bafc98f87d8913ffaee6324ea39dba9: expected output external/local_config_python/_python3/_python3_include/ImDib.h does not exist.
ERROR: /localdata/cameronm/bazel-cache/_bazel_cameronm/4a6a9c9dd102688bd8fbfeb685efb169/external/local_config_python/_python3/BUILD:15:11 Middleman _middlemen/@local_Uconfig_Upython_S_S_Upython3_C_Upython3_Uheaders-BazelCppSemantics_build_arch_k8-fastbuild failed: (Exit 34): Invalid action cache entry 1fbde1c0993f3d186ff6ade516bfd2765bafc98f87d8913ffaee6324ea39dba9: expected output external/local_config_python/_python3/_python3_include/ImDib.h does not exist.
```

Related discussion: https://bazelbuild.slack.com/archives/C01E7TH8XK9/p1670925578798099

**Comment by rwgk** [comment]
I cannot access the slack archive, I'm getting "No account found" when I request access under my corp email. I don't know what I have to do to get access.

pybind11_bazel is only at the level of a minimal viable product without dedicated staffing, and not even a bazel expert around here. I only know just enough to get it to build pybind11_abseil.

If you have ideas for making it work with remote execution, please send a PR. As long as it still builds pybind11_abseil, I'll merge it.

**Comment by cameron-martin** [comment]
This seems to actually work with remote execution, and I must have mis-diagnosed the issue initially. Closing this.
