### ISSUE TITLE
numpy_include rule is missing

### ISSUE THREAD

**Issue by cemlyn007** [pybind/pybind11_bazel#51]
When trying to use the `numpy_headers` rule I noticed that the `numpy_include` rule is missing.
```
local_config_python/BUILD:67:11: Middleman _middlemen/@local_Uconfig_Upython_S_S_Cnumpy_Uheaders-cc_library-compile failed: missing input file '@local_config_python//:numpy_include'
```

**Comment by rwgk** [comment]
Did you find a fix?

We're (unfortunately) not staffed to support this repo, but if you send a fix I'll try it out with pybind11_abseil, which is currently the only use case I have. If that's still working I'll merge.

**Comment by cemlyn007** [comment]
I was going to use it when building Reverb for the M1 and in the end decided not to use the `numpy_include` rule from this repository. I mostly created this issue as a heads up for anyone else that might try to use the rule.

Maybe `numpy_headers` and `numpy_include` should be removed since PyBind is not dependent on NumPy?

FYI: I am a bazel and PyBind noob

**Comment by rwgk** [comment]
Thanks, I think I understand the situation a little better now.

The `numpy_headers` rule was added with af0e2de458d68d45fe4a957d351681e743b3ed47:

```
cc_library(
    name = "numpy_headers",
    hdrs = [":numpy_include"],
    includes = ["numpy_include"],
)
```

But even then there was no `numpy_include`. I think that never existed and the `numpy_headers` rule was an accident from the start. I'll try to remove it.
