### ISSUE TITLE
_get_python_include is wrong for system python on Mac

### ISSUE THREAD

**Issue by cemlyn007** [pybind/pybind11_bazel#52]
I may be wrong but it appears that this line is not perfect?

https://github.com/pybind/pybind11_bazel/blob/b162c7c88a253e3f6b673df0c621aca27596ce6b/python_configure.bzl#L269

With input:
`PYTHON_BIN_PATH='/usr/bin/python3'`
Which points to the system installed version of Python on MacOS.

Calling `_get_python_include` returns: `/Library/Python/3.9/include` which does not exist on my Mac. Instead the headers appear to be located here: `/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/Headers` (ie: `Python.h` etc)

My current work around is not to use the system installed version of Python and am instead using Conda which does not cause this error.

**Comment by rwgk** [comment]
> I may be wrong but it appears that this line is not perfect?

Quite possibly, I'm only ever testing under Linux.

In pybind11_abseil we have this:

```
scripts/build_and_run_tests.sh:export PYTHON_BIN_PATH=`which python3`
```

Could something like that work for you, too? (To get you unblocked quickly.)

Ideally though you're right, it would be better to make pybind11_bazel/python_configure.bzl smarter, but it looks like a bit of a project, doing the right thing in all environments is notoriously tricky.

**Comment by cemlyn007** [comment]
Hi 👋 there is nothing wrong with the logic related to getting the path to the Python binary. Unfortunately, [this](https://github.com/pybind/pybind11_bazel/blob/b162c7c88a253e3f6b673df0c621aca27596ce6b/python_configure.bzl#LL277C13-L277C69) is lying on my machine:
```
% python3 -c "import sysconfig; print(sysconfig.get_path('include'))"
/Library/Python/3.9/include
```
Maybe my system setup is malformed though! I would have to dig into it further on my end. I only created the ticket in case other people have a similar issue.

**Comment by junyer** [comment]
As of the [v2.11.1.bzl.2](https://github.com/pybind/pybind11_bazel/releases/tag/v2.11.1.bzl.2) release, pybind11_bazel uses rules_python and `python_configure.bzl` no longer exists.
