### ISSUE TITLE
Is there an example for pybind11_bazel ?

### ISSUE THREAD

**Issue by OuHangKresnik** [pybind/pybind11_bazel#6]
I'm quite new to pybind11, if there is an example to use pybind11 in bazel that would be great. Just like the pybind cmake examples.

Thanks.

**Comment by yutongs-dmai** [comment]
> I'm quite new to pybind11, if there is an example to use pybind11 in bazel that would be great. Just like the pybind cmake examples.
> 
> Thanks.

@OuHangKresnik Did you find any example?

**Comment by 0x00-pl** [comment]
same question
