### ISSUE TITLE
initial support for rules_python

### ISSUE THREAD

**Issue by junyer** [pybind/pybind11_bazel#64]
See https://github.com/bazelbuild/bazel/issues/8674#issuecomment-1828262381 for background.

For historical reasons, [this](https://github.com/pybind/pybind11_bazel/blob/c65db0ac44ff3cd790a803e4a804e2cc806cf641/python_configure.bzl#L408-L409) logic enforces that `python_version` is `"2"`, `"3"` or `""`. My current thinking is to extend that to permit `"3.<minor>"` and `"DEFAULT"` and "resolve" such versions to `Label`s via `INTERPRETER_LABELS` (and `DEFAULT_PYTHON_VERSION`) as provided by `@pythons_hub//:interpreters.bzl`.

Ping (again), @rickeylev and @rwgk. :)

**Comment by mutongx** [comment]
Thanks @junyer! I was previously unsure about where to ask for help so I ended up with that workaround in my company internal repo. Very happy to see that pybind11_bazel is initiating support for rules_python, and please let me know if you need any testers. I will be here to help.

**Comment by junyer** [comment]
Glad to hear that you are keen, @mutongx. https://github.com/pybind/pybind11_bazel/pull/65 isn't going to fly, unfortunately, but I do want to solve this problem in the not too distant future, so... back to the drawing board. :)

**Comment by rickeylev** [comment]
I just wanted to drop a couple sketches of how I see this likely working. This is based on how Google makes pybind work internally, where the C++ integration is better with the Python rules.

Fundamentally, what we want to to is define a `cc_library` that depends on targets that provide the headers, copts, and linkopts we need. Where do we get that information? From "the toolchain", specifically, the `@rules_python//python/cc:toolchain_type` toolchain.

The end result would look something like this...

```
def pybind11_library(name, ...):
  py_library(name=name, deps=[name + "_cc"], ...)
  cc_library(
    name = name + "_cc",
    deps = [
      "@rules_python//python/cc:current_py_cc_headers",
      "@rules_python//python/cc:current_py_dsos",
      "@rules_python//python/cc:current_py_linkopts",
      "@rules_python//python/cc:current_py_copts",
    ]
)
```

I broke out separate `current_py_*` targets just for illustrative purposes. I'm not entirely sure the granularity that is needed. In any case, think of those targets "magic" `cc_library` targets that rules_python defines that know how to get the right values. e.g., they conceptually look like this:

```
# rules_python/python/cc/BUILD
cc_library(name = "current_py_cc_headers", srcs=["Python.h"])
cc_library(name = "current_py_dsos", srcs="libpython310.so"])
cc_library(name = "current_py_linkopts", linkopts=["-lm", ...], ...)
```

(except they use toolchain stuff to fill the values in).

**Comment by junyer** [comment]
Closing this issue in favour of issue https://github.com/pybind/pybind11_bazel/issues/71 (and PR https://github.com/pybind/pybind11_bazel/pull/72).
