### ISSUE TITLE
No matching toolchains found for types @@rules_python//python/cc:toolchain_type

### ISSUE THREAD

**Issue by axbycc-mark** [pybind/pybind11_bazel#78]
I'm on Windows 10, Visual Studio 2019, Bazel 7.0.2.

I hit `No matching toolchains found for types @@rules_python//python/cc:toolchain_type` in a barebones project with just one attempted pybind_extension target. I have the native python development tools, which ended up installed at `C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64`.

Regular cc_binary / cc_library targets can be built correctly. I wasn't able to understand how python_rules registers toolchains for python/cc:toolchain_type or if I have to manually register a toolchain.  A previous branch of pybind11_bazel that used the python_configure.bzl file built correctly on my system.

Workspace

```
workspace(name = "pybind_bazel_test")
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# pybind
pybind_bazel_version = "1b3b9e6bf151854eeba4e6dd16a0ce759ff81e7b"
http_archive(
  name = "pybind11_bazel",
  strip_prefix = "pybind11_bazel-" + pybind_bazel_version,
  urls = ["https://github.com/pybind/pybind11_bazel/archive/" + pybind_bazel_version + ".zip"],
)
pybind_version = "8b48ff878c168b51fe5ef7b8c728815b9e1a9857"
http_archive(
  name = "pybind11",
  build_file = "@pybind11_bazel//:pybind11-BUILD.bazel",
  strip_prefix = "pybind11-" + pybind_version,
  urls = ["https://github.com/pybind/pybind11/archive/" + pybind_version + ".zip"],
)

```

BUILD
```
load("@pybind11_bazel//:build_defs.bzl", "pybind_extension")

pybind_extension(
    name="example",
    srcs=["example.cpp"]
)

```

Error
```
bazel build example --toolchain_resolution_debug='@@rules_python//python/cc:toolchain_type'
ERROR: C:/users/marki/_bazel_marki/5kqsbpon/external/rules_python/python/cc/BUILD.bazel:14:22: While resolving toolchains for target @@rules_python//python/cc:current_py_cc_headers (52f48c8): No matching toolchains found for types @@rules_python//python/cc:toolchain_type.
To debug, rerun with --toolchain_resolution_debug='@@rules_python//python/cc:toolchain_type'
If platforms or toolchains are a new concept for you, we'd encourage reading https://bazel.build/concepts/platforms-intro.
ERROR: Analysis of target '//:example' failed; build aborted: Analysis failed
```

**Comment by junyer** [comment]
It's probably impossible to use rules_python from a `WORKSPACE` file with Bzlmod enabled. I suggest adopting Bzlmod at least partially: populate a `MODULE.bazel` file to the extent possible; and then keep everything else in a `WORKSPACE.bzlmod` file.

**Comment by axbycc-mark** [comment]
Got it, thanks. What ended up working for me was
- pybind11 + pybind11_bazel defined in the WORKSPACE
- rules_python defined in MODULE.bazel

With this setup, I saw some flashing output that indicated that Bazel was downloading its own python version, which is indicated here https://github.com/bazelbuild/rules_python/blob/main/BZLMOD_SUPPORT.md#differences-in-behavior-from-workspace

**Comment by junyer** [comment]
pybind11 should Just Work™ as a module as well, FWIW, but the key thing in this case is that rules_python installs a hermetic Python toolchain. It's possible to use the local Python toolchain, but rules_python doesn't (yet) offer a simple way to do that, AFAIK, so you would probably have to do something like [this](https://github.com/google/re2/blob/108914d28a79243d4300e7e651cd0a0d5883ca0f/python/setup.py#L92) in the meantime.

**Comment by axbycc-mark** [comment]
In order to make things work as a module, I needed to add the following lines as well to MODULE.bazel

```
pybind11_configure = use_extension("@pybind11_bazel//:internal_configure.bzl", "internal_configure_extension")
use_repo(pybind11_configure, "pybind11")

```

**Comment by wxfred** [comment]
I found that only do these below will build success:

WORKSPACE
```
local_repository(
    name = "pybind11_bazel",
    path = "thirdparty/pybind11_bazel-2.13.6", # I downloaded it to local
)

# bazel will download https://github.com/pybind/pybind11/archive/refs/tags/v2.13.6.tar.gz, even I claim to use the 3.0.1 below
# I don't know why
# new_local_repository(
#     name = "pybind11",
#     build_file = "@pybind11_bazel//:pybind11-BUILD.bazel",
#     path = "thirdparty/pybind11-3.0.1",
# )
```

MODULE.bazel
```
bazel_dep(name = "rules_python", version = "0.34.0")
bazel_dep(name = "pybind11_bazel")
local_path_override(
    module_name = "pybind11_bazel",
    path = "thirdparty/pybind11_bazel-2.13.6",
)
```

Finally, run the command with bzlmod enabled, like
```
bazel test //:basic_test --enable_bzlmod
```
I added `--noenable_bzlmod` to my `.bazelrc` so i need to append `--enable_bzlmod`
