### ISSUE TITLE
Selecting the python version

### ISSUE THREAD

**Issue by dragoscarp** [pybind/pybind11_bazel#79]
When used in a multi python version bzlmod workspace add an attribute to select the python version for `pybind_extension`, `pybind_library` and `pybind_library_test` rules.

**Comment by junyer** [comment]
My understanding is that the `py_binary()` and `py_test()` rules may specify Python versions and that whatever the current Python toolchain happens to be will propagate to other rules as needed. See [this](https://github.com/bazelbuild/rules_python/blob/main/examples/multi_python_versions/libs/my_lib/BUILD.bazel) and [this](https://github.com/bazelbuild/rules_python/blob/main/examples/multi_python_versions/tests/BUILD.bazel) in the rules_python examples for a sense of what I mean. Please correct me if I'm wrong, @rickeylev, or if I'm overlooking some subtlety in this feature request!

**Comment by rickeylev** [comment]
Correct. Library rules shouldn't be specifying a version because that's the responsibility of a higher level rule.

Do you want to force a particular version because you're building something for packaging (e.g. for pypi distribution)? If so, then the rule that performs the packaging (e.g. py_wheel, py_package, or what have you) should use a transition to set the python version.

**Comment by dragoscarp** [comment]
Thank you for the answers!
Maybe I'm missing something, but as an example I think it should be possible to have `py_binary` targets depending on a `pybind_extension` target.
How could I do this for target `version_3_10` or `version_3_9` in this example?
https://github.com/bazelbuild/rules_python/blob/c5c03b2477dd1ce0c06c9dc60bf816995f222bcf/examples/multi_python_versions/tests/BUILD.bazel#L35

**Comment by junyer** [comment]
As per [the documentation](https://github.com/pybind/pybind11_bazel/blob/1b3b9e6bf151854eeba4e6dd16a0ce759ff81e7b/README.md?plain=1#L5-L7), please add the `pybind_extension` target to the `data` attribute – **_not_** the `deps` attribute – of the `py_*` target.

**Comment by dragoscarp** [comment]
Thank you! It seems to work indeed when the `data` attribute is used!
