### ISSUE TITLE
Confused on how to use repo

### ISSUE THREAD

**Issue by TheButlah** [pybind/pybind11_bazel#8]
Hi, 

I'm confused on how to use this repo. I expected to just add it to my WORKSPACE via the `git_repository` command. However, I can't seem to access the `@pybind11//:pybind11` target because its defined in a `pybind11.BUILD` file, instead of a `BUILD` or `BUILD.bazel` file. I also cannot seem to access it via `new_git_repository` and point it to the path of the `pybind11.BUILD` file, because to my knowledge such a file must exist in the local not remote workspace.

Am I doing something wrong or should the build file be renamed?

**Comment by TheButlah** [comment]
Update: I saw PR #7 , so if that is the correct way to move forward, merging that PR would be appreciated

**Comment by dmadisetti** [comment]
@TheButlah #7 was merged if you want to close this
