### ISSUE TITLE
How to embed Python interpreter?

### ISSUE THREAD

**Issue by axbycc-mark** [pybind/pybind11_bazel#80]
Sorry I'm not so good at Bazel. The current doc says "embed Python, add @rules_python//python/cc:current_py_cc_libs as a dependency to your cc_binary."

But this doesn't seem enough because the header "pybind11/embed.h" would not be found. What additional dependencies should I add to build the following minimal example?

```
#include <pybind11/embed.h> // everything needed for embedding
namespace py = pybind11;

int main() {
    py::scoped_interpreter guard{}; // start the interpreter and keep it alive

    py::print("Hello, World!"); // use the Python API
}
```

**Comment by junyer** [comment]
For something like "hello, world" tinkering, it might be easiest to use the `pybind_library_test()` rule, which will provide the headers **_and_** the libraries (i.e. don't specify `@rules_python//python/cc:current_py_cc_libs` in `deps`) and will output a C++ binary. We only just got it working again about a month ago, mind you, so please let me know if you encounter any problems!

**Comment by axbycc-mark** [comment]
I tried this out and I'm getting a runtime exception on Windows 10. Step by step debugging in Visual Studio takes me down into pylifecycle.c from the Python source code, which was originally at  `C:\Users\runneradmin\AppData\Local\Temp\python-build-ppgzl_qt\Python-3.11.7\Python\pylifecycle.c` on my machine. I'm guessing Bazel put it there when it built the default hermetic host python toolchain. Is there a way for Bazel to regenerate this file so that I can continue debugging?

**Comment by junyer** [comment]
Oh, whoa! Now I'm wondering whether such crashing might be related to "[trying to take settings from the local environment](https://github.com/pybind/pybind11_bazel/issues/77#issuecomment-1992105851)" somehow? Apart from that, the hermetic Python toolchains are `indygreg/python-build-standalone` [releases](https://github.com/indygreg/python-build-standalone/releases); Bazel doesn't build Python itself and so neither rules_python nor pybind11_bazel can do much to help here, AFAIK.

**Comment by axbycc-mark** [comment]
I've investigated this issue much more and I posted my findings under the issue you linked. The resolution must wait on some new code on the python_rules side. It is also blocked on a bug fix for https://github.com/bazelbuild/rules_python/issues/1823 which is currently in progress.

**Comment by junyer** [comment]
Many thanks for digging into this! :D
