### ISSUE TITLE
How do I create a .so file?

### ISSUE THREAD

**Issue by seanngpack** [pybind/pybind11_bazel#84]
pybind version: 2.11.1 (im stuck on bazel 5.4 so I have to use this version)

Hi, sorry this may be a really silly question but how do I generate and retrieve a .so file after building my c++ `cc_binary` target? My use case is a little weird--I want to build a .so file and copy the file into a separate repository to use.

Cant find the .so file in my Bazel-out folder.

example BUILD file:

```
load("@pybind11_bazel//:build_defs.bzl", "pybind_extension")

cc_binary(
    name = "my_binary",
    srcs = ["main.cpp"],
    deps = [
            "@pybind11//:pybind11_embed",
            ]
```

**Comment by junyer** [comment]
To obtain a `.so`/`.pyd` file, use the `pybind_extension()` rule instead; the RE2 Python bindings do [this](https://github.com/google/re2/blob/2b354c6ad0d0479dcff68dab23fb0d1143a482c2/python/BUILD.bazel#L10-L25), for example.

**Comment by seanngpack** [comment]
thanks for the response @junyer, works now!

**Comment by junyer** [comment]
Glad to hear. :)
