### ISSUE TITLE
Updating the module version at https://registry.bazel.build/modules/pybind11_bazel

### ISSUE THREAD

**Issue by apronchenkov** [pybind/pybind11_bazel#99]
Could you please update the module version at https://registry.bazel.build/modules/pybind11_bazel and possibly create a new release?

The `MODULE.bazel` file indicates that the current version is `2.13.1`, but the version available from the repository is `2.12.0`.

+ @jiawen

**Comment by apronchenkov** [comment]
Extra: In my case, it would also be useful to have #98 included in the release (it addresses #94). Thanks!

**Comment by jiawen** [comment]
@hofbi - I merged #101.

@apronchenkov - I merged #98 (thanks @hofbi) a few weeks ago.

My day job is keeping me pretty busy but I'll try to find a few cycles over the next few days to figure out how to cut a release and upstream it to BCR.

**Comment by hofbi** [comment]
https://registry.bazel.build/modules/pybind11_bazel/2.13.6 was published 9 hours ago
